### ISSUE TITLE
TypeError: read_csv() got an unexpected keyword argument 'byte_range'

### ISSUE THREAD

**Issue by trstovall** [rapidsai/dask-cudf#107]
```
>>> from numpy import dtype
>>> from dask_cudf import read_csv
>>> with open('const.csv', 'w') as f:
...   f.write('1,2,3\n')
... 
6
>>> read_csv('const.csv', names=list('abc'), dtype=[dtype('i')]*3).compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.7/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/conda/lib/python3.7/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 500, in get_sync
    return get_async(apply_sync, 1, dsk, keys, **kwargs)
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 446, in get_async
    fire_task()
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 442, in fire_task
    callback=queue.put)
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 489, in apply_sync
    res = func(*args, **kwds)
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 235, in execute_task
    result = pack_exception(e, dumps)
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/conda/lib/python3.7/site-packages/dask/compatibility.py", line 93, in apply
    return func(*args, **kwargs)
TypeError: read_csv() got an unexpected keyword argument 'byte_range'
```
dask_cudf is master branch, cudf is branch-0.6.  Also fails with cudf on master branch.

**Comment by mrocklin** [comment]
You need cudf branch-0.6
