### ISSUE TITLE
What works and what doesn't doc

### ISSUE THREAD

**Issue by mrocklin** [rapidsai/dask-cudf#146]
Folks have asked for a document explaining what works and what doesn't.  I wrote up a rough draft.  Where should this live?  @randerzander @taureandyernv 

```rst
What works with Dask and cuDF
=============================

This page discusses what works and doesn't work with Dask and cuDF today.
This is somewhat complex because Pandas, Dask DataFrame, and cuDF all evolve
independently, and are at different states of development.

What works
----------

-  Data ingestion
    -  ``dask_cudf.read_csv``
    -  Use standard Dask ingestion with Pandas, then convert to cuDF (For
      Parquet and other formats this is often decently fast)
-  Linear operations
    -  Element-wise operations:  ``df.x + df.y``, ``df ** 2``
    -  Assignment: ``df['z'] = df.x + df.y``
    -  Row-wise selections:  ``df[df.x > 0]``
    -  Loc:  ``df.loc['2001-01-01': '2005-02-02']``
    -  Date time/string accessors:  ``df.timestamp.dt.dayofweek``
    -  ... and most similar operations in this category that are already implemented in cuDF
-  Reductions
    -  Like ``sum``, ``mean``, ``max``, ``count``, and so on on ``Series`` objects
    -  ~~Support for reductions on full dataframes~~
    -  ~~``std``~~
    -  Custom reductions with `dask.dataframe.reduction <http://docs.dask.org/en/latest/dataframe-api.html#dask.dataframe.Series.reduction>`
-  Groupby aggregations
    -  On single columns: ``df.groupby('x').y.max()``
    -  With custom aggregations:
    -  ~~groupby standard deviation~~
    -  ~~grouping on multiple columns~~
    -  ~~groupby agg for multiple outputs~~
-  Joins:
    -  On full unsorted columns: ``left.merge(right, on='id')`` (expensive)
    -  On sorted indexes: ``left.merge(right, left_index=True, right_index=True)`` (fast)
    -  On large and small dataframes: ``left.merge(cudf_df, on='id')`` (fast)
-  ~~Rolling operations~~
-  Converting to and from other forms
    -  Dask + Pandas to Dask + cuDF ``df.map_partitions(cudf.from_pandas)``
    -  Dask + cuDF to Dask + Pandas ``df.map_partitions(lambda df: df.to_pandas())``
    -  cuDF to Dask + cuDF: ``dask.dataframe.from_pandas(df, npartitions=20)``
    -  Dask + cuDF to cuDF: ``df.compute()``

Additionally all generic Dask operations, like ``compute``, ``persist``,
``visualize`` and so on work regardless.


Developing the API
------------------

Above we mention the following:

> and most similar operations in this category that are already implemented in cuDF

This is because it is difficult to create a comprehensive list of operations in
the cuDF and Pandas libraries.  The API is large enough to be difficult to track
effectively.  For any operation that operates row-wise like ``fillna`` or
``query`` things will likely, but not certainly work.  If operations don't work
it is often due to a slight inconsistency between Pandas and cuDF that is
generally easy to fix.  We encourage users to look at the `cuDF issue
tracker <https://github.com/rapidsai/cudf/issues>`_ to see if their issue has
already been reported and, if not,
`raise a new issue <https://github.com/rapidsai/cudf/issues/new>`_.


Navigating the API
------------------

This project reuses the
`Dask DataFrame <https://dask.org/en/latest/dataframes.html>`_ project, which
was originally designed for Pandas, with the newer library cuDF.  Because we use
the same Dask classes for both projects there are often methods that are
implemented for Pandas, but not yet for cuDF.  As a result users looking at the
full Dask DataFrame API can be misleading, and often lead to frustration when
operations that are advertised in the Dask API do not work as expected with
cuDF.  We apologize for this in advance.
```

**Comment by randerzander** [comment]
cudf and dask-cudf are distinct projects, and thus have two distinct APIs.

However, the considerable overlap in user-base, supported functionality, and APIs between the two makes me lean towards adding this as a new page (or at least linked from)  [cudf's API docs](https://rapidsai.github.io/projects/cudf/en/latest).

@kkraus14 @mrocklin any objection to that for now?

**Comment by mrocklin** [comment]
Fine by me

**Comment by beckernick** [comment]
Are we able to do groupby-aggregations on single columns with the `agg` API? Problem may be on my end, but I'm seeing:

```
import nvstrings
import cudf
import dask_cudf

df = cudf.DataFrame([('a', list(range(20))),
('b', list(reversed(range(20)))),
('c', list(range(20)))])

df['agg_col1'] = [1 if x % 2 == 0 else 0 for x in range(len(df))]
df['agg_col2'] = [1 if x % 3 == 0 else 0 for x in range(len(df))]

ddf = dask_cudf.from_cudf(df, npartitions=2)

print(ddf.groupby('agg_col1').sum().compute())
print()
print(ddf.groupby('agg_col1').a.sum().compute())
print()
print(ddf.groupby('agg_col1').a.agg(['sum']))
     a    b    c  agg_col2
0  100   90  100         3
1   90  100   90         4

0    100
1     90
dtype: int64

     a    b    c  agg_col2
cudf_groupby_level_index
0  100   90  100         3
1   90  100   90         4

0    100
1     90
dtype: int64

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    159     try:
--> 160         yield
    161     except Exception as e:

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3682     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3683         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3684 

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/groupby.py in _groupby_apply_funcs(df, *index, **kwargs)
    647 
--> 648     return pd.DataFrame(result)
    649 

/conda/envs/cudf/lib/python3.7/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    391         elif isinstance(data, dict):
--> 392             mgr = init_dict(data, index, columns, dtype=dtype)
    393         elif isinstance(data, ma.MaskedArray):

/conda/envs/cudf/lib/python3.7/site-packages/pandas/core/internals/construction.py in init_dict(data, index, columns, dtype)
    211 
--> 212     return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
    213 

/conda/envs/cudf/lib/python3.7/site-packages/pandas/core/internals/construction.py in arrays_to_mgr(arrays, arr_names, index, columns, dtype)
     50     if index is None:
---> 51         index = extract_index(arrays)
     52     else:

/conda/envs/cudf/lib/python3.7/site-packages/pandas/core/internals/construction.py in extract_index(data)
    307         if not indexes and not raw_lengths:
--> 308             raise ValueError('If using all scalar values, you must pass'
    309                              ' an index')

ValueError: If using all scalar values, you must pass an index

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-098c49aee935> in <module>
     16 print(ddf.groupby('agg_col1').a.sum().compute())
     17 print()
---> 18 print(ddf.groupby('agg_col1').a.agg(['sum']))

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/groupby.py in agg(self, arg, split_every, split_out)
   1235     @derived_from(pd.core.groupby.SeriesGroupBy)
   1236     def agg(self, arg, split_every=None, split_out=1):
-> 1237         return self.aggregate(arg, split_every=split_every, split_out=split_out)

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/groupby.py in aggregate(self, arg, split_every, split_out)
   1224     @derived_from(pd.core.groupby.SeriesGroupBy)
   1225     def aggregate(self, arg, split_every=None, split_out=1):
-> 1226         result = super(SeriesGroupBy, self).aggregate(arg, split_every=split_every, split_out=split_out)
   1227         if self._slice:
   1228             result = result[self._slice]

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/groupby.py in aggregate(self, arg, split_every, split_out)
   1047                    ),
   1048                    token='aggregate', split_every=split_every,
-> 1049                    split_out=split_out, split_out_setup=split_out_on_index)
   1050 
   1051     @insert_meta_param_description(pad=12)

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/core.py in apply_concat_apply(args, chunk, aggregate, combine, meta, token, chunk_kwargs, aggregate_kwargs, combine_kwargs, split_every, split_out, split_out_setup, split_out_setup_kwargs, **kwargs)
   3639 
   3640     if meta is no_default:
-> 3641         meta_chunk = _emulate(chunk, *args, udf=True, **chunk_kwargs)
   3642         meta = _emulate(aggregate, _concat([meta_chunk]), udf=True,
   3643                         **aggregate_kwargs)

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/core.py in _emulate(func, *args, **kwargs)
   3681     """
   3682     with raise_on_meta_error(funcname(func), udf=kwargs.pop('udf', False)):
-> 3683         return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
   3684 
   3685 

/conda/envs/cudf/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/utils.py in raise_on_meta_error(funcname, udf)
    175                 "{2}")
    176         msg = msg.format(" in `{0}`".format(funcname) if funcname else "", repr(e), tb)
--> 177         raise ValueError(msg)
    178 
    179 

ValueError: Metadata inference failed in `_groupby_apply_funcs`.

You have supplied a custom function and Dask is unable to 
determine the type of output that that function returns. 

To resolve this please provide a meta= keyword.
The docstring of the Dask function you ran should have more information.

Original error is below:
------------------------
ValueError('If using all scalar values, you must pass an index')

Traceback:
---------
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/utils.py", line 160, in raise_on_meta_error
    yield
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/core.py", line 3683, in _emulate
    return func(*_extract_meta(args, True), **_extract_meta(kwargs, True))
  File "/conda/envs/cudf/lib/python3.7/site-packages/dask/dataframe/groupby.py", line 648, in _groupby_apply_funcs
    return pd.DataFrame(result)
  File "/conda/envs/cudf/lib/python3.7/site-packages/pandas/core/frame.py", line 392, in __init__
    mgr = init_dict(data, index, columns, dtype=dtype)
  File "/conda/envs/cudf/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 212, in init_dict
    return arrays_to_mgr(arrays, data_names, index, columns, dtype=dtype)
  File "/conda/envs/cudf/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 51, in arrays_to_mgr
    index = extract_index(arrays)
  File "/conda/envs/cudf/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 308, in extract_index
    raise ValueError('If using all scalar values, you must pass'
```

But no clear place to supply the `meta` keyword a DataFrame.

Environment, with dask_cudf from the `41c95a89f7c68af0e7547db4f44a1ec84a43d5d4` commit on March 8.
```
# packages in environment at /conda/envs/cudf:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
arrow-cpp                 0.12.0           py37h0e61e49_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl  
bleach                    3.1.0                      py_0    conda-forge
boost                     1.68.0          py37h8619c78_1001    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.1.23                     0  
certifi                   2018.11.29               py37_0  
cffi                      1.12.0           py37h9745a5d_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                      pypi_0    pypi
cloudpickle               0.7.0                      py_0    conda-forge
cmake                     3.13.2            h8d4ced6_1000    conda-forge
commonmark                0.8.1                      py_0    conda-forge
cryptography              2.5              py37hb7f436b_0    conda-forge
cudf                      0.6.0.dev0+413.gc73bd61.dirty          pypi_0    pypi
curl                      7.64.0               h646f8bb_0    conda-forge
cython                    0.29.5           py37hf484d3e_0    conda-forge
cytoolz                   0.9.0.1         py37h14c3975_1001    conda-forge
dask-core                 1.1.1                      py_0    conda-forge
dask-cudf                 0.0.1+256.g41c95a8          pypi_0    pypi
decorator                 4.3.2                      py_0    conda-forge
distributed               1.25.3                   py37_0    conda-forge
docutils                  0.14                  py37_1001    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
future                    0.17.1                py37_1000    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
intel-openmp              2019.1                      144  
ipykernel                 5.1.0           py37h24bf2e0_1002    conda-forge
ipython                   7.2.0           py37h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.13.2                py37_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jsonschema                3.0.0a3               py37_1000    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.3                   py37_0  
jupyterlab_server         0.2.0                    py37_0  
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.64.0               h01ee5af_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdf-cffi               0.6.0                    pypi_0    pypi
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libprotobuf               3.6.1             hdbcaa40_1000    conda-forge
librmm-cffi               0.5.0                    pypi_0    pypi
libsodium                 1.0.16            h14c3975_1001    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libuv                     1.26.0               h14c3975_0    conda-forge
llvmlite                  0.27.0           py37hf484d3e_0    numba
markdown                  2.6.11                   pypi_0    pypi
markupsafe                1.1.0           py37h14c3975_1000    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py37h14c3975_1    conda-forge
mkl_random                1.0.2            py37h637b7d7_2    conda-forge
more-itertools            4.3.0                 py37_1000    conda-forge
msgpack-python            0.6.1            py37h6bb024c_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nbsphinx                  0.4.2                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  5.7.4                 py37_1000    conda-forge
numba                     0.42.0          np115py37hf484d3e_0    numba
numpy                     1.15.4           py37h7e9f1db_0  
numpy-base                1.15.4           py37hde5b4d6_0  
numpydoc                  0.8.0                      py_1    conda-forge
nvstrings-cuda92          0.0.0.dev0               pypi_0    pypi
openssl                   1.0.2r               h7b6447c_0  
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.1           py37hf484d3e_0    conda-forge
pandoc                    2.6                           1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         4    conda-forge
parso                     0.3.4                      py_0    conda-forge
pexpect                   4.6.0                 py37_1000    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.0.2                   py37_0    conda-forge
pluggy                    0.8.1                      py_0    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.8                      py_0    conda-forge
psutil                    5.5.0            py37h14c3975_0    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
py                        1.7.0                      py_0    conda-forge
pyarrow                   0.12.0           py37hbbcf98d_2    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyrsistent                0.14.10          py37h14c3975_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
pytest                    4.2.1                    py37_0    conda-forge
python                    3.7.1             hd21baee_1000    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pyyaml                    3.13            py37h14c3975_1001    conda-forge
pyzmq                     17.1.2          py37h6afc9c9_1001    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
recommonmark              0.5.0                      py_0    conda-forge
requests                  2.21.0                py37_1000    conda-forge
rhash                     1.3.6             h14c3975_1001    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sphinx                    1.8.4                    py37_0    conda-forge
sphinx-markdown-tables    0.0.9                    pypi_0    pypi
sphinx_rtd_theme          0.4.3                      py_0    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tblib                     1.3.2                    pypi_0    pypi
terminado                 0.8.1                 py37_1001    conda-forge
testpath                  0.4.2                 py37_1000    conda-forge
thrift-cpp                0.12.0            h23e226f_1001    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                    pypi_0    pypi
tornado                   5.1.1           py37h14c3975_1000    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.0                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.2.5             hf484d3e_1006    conda-forge
zict                      0.1.4                    pypi_0    pypi
zlib                      1.2.11            h14c3975_1004    conda-forge
```

**Comment by mrocklin** [comment]
No, the only groupby aggregations that work are of the form

    -  On single columns: ``df.groupby('x').y.max()``

**Comment by beckernick** [comment]
Got it, thanks! I think we may want to clarify this part of the groupby section:

```
With custom aggregations:
    -  ~~groupby standard deviation~~
    -  ~~grouping on multiple columns~~
    -  ~~groupby agg for multiple outputs~~
```

My initial read on this was that we could use the agg API, which I was surprised by (hence the test just now).

**Comment by mrocklin** [comment]
Good idea

**Comment by randerzander** [comment]
Closed by https://github.com/rapidsai/cudf/pull/1218
