### ISSUE TITLE
`dask/cudf` runs OOM and core dumps on operations following `GroupBy.agg`

### ISSUE THREAD

**Issue by trstovall** [rapidsai/dask-cudf#283]
```
>>> df
<dask_cudf.DataFrame | 3750 tasks | 96 npartitions>
>>> 
>>> df = df.groupby(
...     [col + '_dup' for col in groupby_key]
... )
>>> df
<dask.dataframe.groupby.DataFrameGroupBy object at 0x7fc600b82e48>
>>> 
>>> df = df.agg({
...     **{'retail_price': 'sum', 'unit_qty': 'sum'},
...     **{k: 'min' for k in groupby_key}
... })
>>> 
>>> df
<dask_cudf.DataFrame | 3861 tasks | 1 npartitions>
>>> 
>>> df = df.reset_index(
...     '_'
... )
WARNING: Logging before flag parsing goes to stderr.
E0618 19:57:05.578486 140486081763072 driver.py:321] Call to cuMemcpyDtoD results in CUDA_ERROR_INVALID_VALUE
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/conda/lib/python3.7/site-packages/dask_cudf/core.py", line 420, in reset_index
    sizes = np.asarray(compute(*map(delayed(len), dfs)))
  File "/conda/lib/python3.7/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/conda/lib/python3.7/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/conda/lib/python3.7/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 118, in _execute_task
    args2 = [_execute_task(a, cache) for a in args]
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 118, in <listcomp>
    args2 = [_execute_task(a, cache) for a in args]
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/conda/lib/python3.7/site-packages/dask/optimization.py", line 942, in __call__
    dict(zip(self.inkeys, args)))
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 149, in get
    result = _execute_task(task, cache)
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/conda/lib/python3.7/site-packages/dask/dataframe/methods.py", line 163, in assign
    return df.assign(**kwargs)
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 377, in assign
    new = self.copy()
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 934, in copy
    df._cols[k] = self._cols[k].copy(deep)
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/series.py", line 163, in copy
    result._column = self._column.copy(deep)
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/column.py", line 357, in copy
    deep = self.copy_data()
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/column.py", line 349, in copy_data
    return self.replace(data=self.data.copy())
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/dataframe/buffer.py", line 189, in copy
    return Buffer(mem=cudautils.copy_array(self.mem),
  File "/conda/lib/python3.7/site-packages/cudf-0.8.0a1+938.g1ebf10f-py3.7-linux-x86_64.egg/cudf/utils/cudautils.py", line 129, in copy_array
    out.copy_to_device(arr)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 188, in copy_to_device
    _driver.device_to_device(self, ary, self.alloc_size, stream=stream)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1874, in device_to_device
    fn(device_pointer(dst), device_pointer(src), size, *varargs)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 293, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/conda/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 328, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuMemcpyDtoD results in CUDA_ERROR_INVALID_VALUE
>>> terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::allocate(): RMM_ALLOC: unspecified launch failure
Aborted (core dumped)
```

**Comment by mrocklin** [comment]
Does the output fit in memory of a single GPU?  If not, you might want to try the `split_out=` parameter

**Comment by trstovall** [comment]
@mrocklin To what is `split_out` a parameter?  Can you point me to docs?  Why is compute being triggered before `.compute()`?

**Comment by trstovall** [comment]
Why does `GroupBy.agg` reduce many partitions to a single partition?

**Comment by mrocklin** [comment]
> To what is split_out a parameter?

It determines the number of output partitions.  Try setting it to 10 or so

> Why is compute being triggered before .compute()?

I don't know

> Why does .groupby(...).agg reduce many partitions to a single partition?

That's the way that the algorithms work by default.  Most aggregation algorithms default to returning a single small result

**Comment by trstovall** [comment]
Here is with setting `split_out`.

```python
>>> df.head()
<cudf.DataFrame ncols=18 nrows=5 >
>>> 
>>> 
>>> nparts = df.npartitions
>>> df = df.groupby(
...     [col + '_dup' for col in groupby_key]
... )
>>> 
>>> df
<dask.dataframe.groupby.DataFrameGroupBy object at 0x7fed0c7c0be0>
>>> df = df.agg(
...     {
...         **{'retail_price': 'sum', 'unit_qty': 'sum'},
...         **{k: 'min' for k in groupby_key}
...     },
...     split_out=nparts
... )
>>> df
<dask_cudf.DataFrame | 14598 tasks | 96 npartitions>
>>> df.reset_index('_')
Segmentation fault (core dumped)
```
After the seg-fault:
```bash
root@f341dcc80109:~# nvidia-smi 
Wed Jun 19 15:59:50 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 410.79       Driver Version: 410.79       CUDA Version: 10.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 00000000:05:00.0 Off |                    0 |
| N/A   37C    P0    51W / 300W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  Off  | 00000000:06:00.0 Off |                    0 |
| N/A   32C    P0    34W / 300W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  Off  | 00000000:84:00.0 Off |                    0 |
| N/A   29C    P0    34W / 300W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  Off  | 00000000:85:00.0 Off |                    0 |
| N/A   34C    P0    34W / 300W |      0MiB / 16280MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

**Comment by trstovall** [comment]
Stack trace from a different run:
```python
>>> df = df.reset_index('_')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/lib/python3.7/site-packages/dask_cudf/core.py", line 420, in reset_index
    sizes = np.asarray(compute(*map(delayed(len), dfs)))
  File "/conda/lib/python3.7/site-packages/dask/base.py", line 398, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/conda/lib/python3.7/site-packages/dask/threaded.py", line 76, in get
    pack_exception=pack_exception, **kwargs)
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 462, in get_async
    raise_exception(exc, tb)
  File "/conda/lib/python3.7/site-packages/dask/compatibility.py", line 112, in reraise
    raise exc
  File "/conda/lib/python3.7/site-packages/dask/local.py", line 230, in execute_task
    result = _execute_task(task, data)
  File "/conda/lib/python3.7/site-packages/dask/core.py", line 119, in _execute_task
    return func(*args2)
  File "/conda/lib/python3.7/site-packages/dask/dataframe/core.py", line 3552, in hash_shard
    h = hash_pandas_object(h, index=False)
  File "/conda/lib/python3.7/site-packages/pandas/core/util/hashing.py", line 119, in hash_pandas_object
    raise TypeError("Unexpected type for hashing %s" % type(obj))
TypeError: Unexpected type for hashing <class 'cudf.dataframe.multiindex.MultiIndex'>
>>> WARNING: Logging before flag parsing goes to stderr.
E0619 15:51:04.343947 139627935540992 driver.py:321] Call to cuMemcpyDtoD results in CUDA_ERROR_INVALID_VALUE
E0619 15:51:04.754749 139626870191872 driver.py:321] Call to cuMemcpyDtoD results in CUDA_ERROR_INVALID_VALUE
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  rmm_allocator::deallocate(): RMM_FREE: __global__ function call is not configured
Aborted (core dumped)
```

**Comment by kkraus14** [comment]
@trstovall We have an entire groupby refactor coming down the pipes where I'd like to hold off on this if possible until after it's merged as it will likely alleviate some of the memory pressure you're experiencing here.
