### ISSUE TITLE
dask_cudf.DataFrame fails to compute empty dataframe

### ISSUE THREAD

**Issue by trstovall** [rapidsai/dask-cudf#81]
Repro:
```
>>> y
<dask_cudf.DataFrame | 0 tasks | 0 npartitions>
>>> y.compute()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py", line 156, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py", line 398, in compute
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask/base.py", line 398, in <listcomp>
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf-0+unknown-py3.7.egg/dask_cudf/core.py", line 45, in finalize
    return cudf.concat(results)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf-0+unknown-py3.7-linux-x86_64.egg/cudf/multi.py", line 21, in concat
    raise ValueError("Need at least one object to concatenate")
ValueError: Need at least one object to concatenate
```

**Comment by mrocklin** [comment]
I'm curious, how did you get to a state where you have zero partitions?  Also, are you using master or latest release?

**Comment by trstovall** [comment]
See issue #80 for a reproduction of zero partitions.
I'm using the version of dask_cudf that is packaged with Docker container `rapidsai/rapidsai:0.5-cuda10.0-base-ubuntu16.04-gcc5-py3.7`.

**Comment by mrocklin** [comment]
Yup.  I noticed.  Should have pinged back here.  I've reported a couple things that need to change upstream in cudf and they're working on them now.  Usually these happen within a few days.

You might want to track the dask label in the cudf repository here: https://github.com/rapidsai/cudf/issues?q=is%3Aissue+is%3Aopen+label%3Adask

**Comment by mrocklin** [comment]
Does this still arise?  Now that we've removed the buggy implementation of `dask_cudf.from_cudf` are there other cases where we can end up with zero partitions?

**Comment by mrocklin** [comment]
Now that #80 is closed I'm going to close this as well. If there is some way to create dask dataframes with zero partitions I'd love to hear more about it.
