### ISSUE TITLE
dask_cudf.from_cudf fails when npartitions set to zero

### ISSUE THREAD

**Issue by trstovall** [rapidsai/dask-cudf#83]
Repro:
```
>>> import dask_cudf, cudf
>>> dask_cudf.from_cudf(cudf.DataFrame(), npartitions=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf-0+unknown-py3.7.egg/dask_cudf/core.py", line 723, in from_cudf
    chunksize = int(ceil(nrows / npartitions))
ZeroDivisionError: division by zero
```

**Comment by mrocklin** [comment]
The answer to this is probably to just use `dd.from_pandas` rather than `dask_cudf.from_cudf`.  I'm in the process of removing the latter function to avoid this confusion now.

**Comment by mrocklin** [comment]
I believe that this has been fixed.  `dask_cudf.from_cudf` is now just `dd.from_pandas`.  Closing.
