### ISSUE TITLE
dask_cudf.from_cudf fails for empty cudf.DataFrame

### ISSUE THREAD

**Issue by trstovall** [rapidsai/dask-cudf#84]
Repro:
```
>>> import dask_cudf, cudf
>>> dask_cudf.from_cudf(cudf.DataFrame(), npartitions=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf-0+unknown-py3.7.egg/dask_cudf/core.py", line 723, in from_cudf
    chunksize = int(ceil(nrows / npartitions))
ZeroDivisionError: division by zero
>>> dask_cudf.from_cudf(cudf.DataFrame(), npartitions=1)
ERROR:Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/conda/envs/rapids/lib/python3.7/site-packages/dask_cudf-0+unknown-py3.7.egg/dask_cudf/core.py", line 728, in from_cudf
    data = data.sort_index(ascending=True)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf-0+unknown-py3.7-linux-x86_64.egg/cudf/dataframe/dataframe.py", line 885, in sort_index
    return self._sort_by(self.index.argsort(ascending=ascending))
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf-0+unknown-py3.7-linux-x86_64.egg/cudf/dataframe/index.py", line 72, in argsort
    return self.as_column().argsort(ascending=ascending)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf-0+unknown-py3.7-linux-x86_64.egg/cudf/dataframe/columnops.py", line 66, in argsort
    _, inds = self.sort_by_values(ascending=ascending)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf-0+unknown-py3.7-linux-x86_64.egg/cudf/dataframe/numerical.py", line 138, in sort_by_values
    index=sort_inds.data.mem)
  File "/conda/envs/rapids/lib/python3.7/site-packages/cudf-0+unknown-py3.7-linux-x86_64.egg/cudf/utils/cudautils.py", line 333, in gather
    gpu_gather.forall(index.size)(data, index, out)
  File "/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/compiler.py", line 235, in __call__
    sharedmem=self.sharedmem)(*args)
  File "/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/compiler.py", line 497, in __call__
    sharedmem=self.sharedmem)
  File "/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/compiler.py", line 571, in _kernel_call
    cu_func(*kernelargs)
  File "/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1514, in __call__
    self.sharedmem, streamhandle, args)
  File "/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 1558, in launch_kernel
    None)
  File "/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 290, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/conda/envs/rapids/lib/python3.7/site-packages/numba/cuda/cudadrv/driver.py", line 325, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuLaunchKernel results in CUDA_ERROR_INVALID_VALUE
```

**Comment by mrocklin** [comment]
Thanks for the bug report @trstovall .  Looking at the traceback this seems to be an issue with cudf.  I've reported upstream at https://github.com/rapidsai/cudf/issues/984 .  Closing this.
